// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateItem(arg1) {
  return window['go']['main']['App']['CreateItem'](arg1);
}

export function CreateLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLink'](arg1, arg2, arg3);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function DeleteLink(arg1) {
  return window['go']['main']['App']['DeleteLink'](arg1);
}

export function GetItem(arg1) {
  return window['go']['main']['App']['GetItem'](arg1);
}

export function GetItemLinks(arg1) {
  return window['go']['main']['App']['GetItemLinks'](arg1);
}

export function GetRecentItems(arg1) {
  return window['go']['main']['App']['GetRecentItems'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}

export function UpdateItem(arg1) {
  return window['go']['main']['App']['UpdateItem'](arg1);
}
