// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { database } from "../models";

export function CreateItem(arg1: database.Item): Promise<number>;

export function CreateLink(
  arg1: number,
  arg2: number,
  arg3: string,
): Promise<void>;

export function DeleteItem(arg1: number): Promise<void>;

export function DeleteLink(arg1: number): Promise<void>;

export function GetItem(arg1: number): Promise<database.Item>;

export function GetItemLinks(arg1: number): Promise<Array<database.Link>>;

export function GetRecentItems(arg1: number): Promise<Array<database.Item>>;

export function GetStats(): Promise<Record<string, number>>;

export function Greet(arg1: string): Promise<string>;

export function SearchItems(arg1: string): Promise<Array<database.Item>>;

export function UpdateItem(arg1: database.Item): Promise<void>;
