// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';
import {settings} from '../models';

export function AddRecentSearch(arg1:string):Promise<void>;

export function CheckpointDatabase():Promise<void>;

export function CleanOrphanedLinks():Promise<number>;

export function CreateItem(arg1:database.Item):Promise<number>;

export function CreateLink(arg1:number,arg2:number,arg3:string):Promise<void>;

export function CreateLinkOrRemoveTags(arg1:number,arg2:string):Promise<main.LinkOrTagResult>;

export function DeleteItem(arg1:number):Promise<void>;

export function DeleteItemImage(arg1:number):Promise<void>;

export function DeleteLink(arg1:number):Promise<void>;

export function DeleteLinkByItems(arg1:number,arg2:number):Promise<void>;

export function DeleteLiteraryTerm(arg1:number):Promise<void>;

export function DeleteSavedSearch(arg1:string):Promise<void>;

export function ExportToJSON():Promise<string>;

export function ExportToMarkdown():Promise<string>;

export function GetAllCliches():Promise<Array<database.Cliche>>;

export function GetAllItems():Promise<Array<database.Item>>;

export function GetAllLinks():Promise<Array<database.Link>>;

export function GetAllLiteraryTerms():Promise<Array<database.LiteraryTerm>>;

export function GetAllNames():Promise<Array<database.Name>>;

export function GetAllSettings():Promise<Record<string, any>>;

export function GetAllSources():Promise<Array<database.Source>>;

export function GetDanglingLinks():Promise<Array<Record<string, any>>>;

export function GetDatabaseFileSize():Promise<number>;

export function GetDatabasePath():Promise<string>;

export function GetDuplicateItems():Promise<Array<Record<string, any>>>;

export function GetEnvLocation():Promise<string>;

export function GetEnvVars():Promise<Record<string, string>>;

export function GetExtendedStats():Promise<database.DashboardStats>;

export function GetImageCacheInfo():Promise<main.ImageCacheInfo>;

export function GetItem(arg1:number):Promise<database.Item>;

export function GetItemByWord(arg1:string):Promise<database.Item>;

export function GetItemImage(arg1:number):Promise<string>;

export function GetItemLinks(arg1:number):Promise<Array<database.Link>>;

export function GetItemsWithUnknownTypes():Promise<Array<Record<string, any>>>;

export function GetItemsWithoutDefinitions():Promise<Array<Record<string, any>>>;

export function GetLinkedItemsNotInDefinition():Promise<Array<Record<string, any>>>;

export function GetMarkedItems():Promise<Array<database.Item>>;

export function GetNavigationHistory():Promise<Array<database.Item>>;

export function GetOrphanedItems():Promise<Array<Record<string, any>>>;

export function GetRandomItem():Promise<database.Item>;

export function GetRecentItems(arg1:number):Promise<Array<database.Item>>;

export function GetRecentSearches():Promise<Array<string>>;

export function GetSavedSearches():Promise<Array<settings.SavedSearch>>;

export function GetSelfReferentialItems():Promise<Array<Record<string, any>>>;

export function GetSettings():Promise<settings.Settings>;

export function GetStats():Promise<Record<string, number>>;

export function GetTTSCacheInfo():Promise<main.TTSCacheInfo>;

export function GetTopHubs(arg1:number):Promise<Array<database.HubItem>>;

export function GetUnknownTags():Promise<Array<Record<string, any>>>;

export function GetUnlinkedReferences():Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function MergeDuplicateItems(arg1:number,arg2:Array<number>):Promise<void>;

export function MergeLiteraryTerm(arg1:number):Promise<void>;

export function RemoveRecentSearch(arg1:string):Promise<void>;

export function RunAdHocQuery(arg1:string):Promise<Array<Record<string, any>>>;

export function SaveCurrentSearch(arg1:string):Promise<void>;

export function SaveIncomingCollapsed(arg1:boolean):Promise<void>;

export function SaveItemImage(arg1:number,arg2:string):Promise<void>;

export function SaveLastView(arg1:string):Promise<void>;

export function SaveLastWord(arg1:number):Promise<void>;

export function SaveLeftbarWidth(arg1:number):Promise<void>;

export function SaveOutgoingCollapsed(arg1:boolean):Promise<void>;

export function SaveReportItemHealthCollapsed(arg1:boolean):Promise<void>;

export function SaveReportLinkIntegrityCollapsed(arg1:boolean):Promise<void>;

export function SaveRevealMarkdown(arg1:boolean):Promise<void>;

export function SaveSearch(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function SaveTabSelection(arg1:string,arg2:string):Promise<void>;

export function SaveTableSort(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SaveWindowPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SearchItems(arg1:string):Promise<Array<database.Item>>;

export function SearchItemsWithOptions(arg1:database.SearchOptions):Promise<Array<database.Item>>;

export function SelectExportFolder():Promise<string>;

export function SpeakWord(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.TTSResult>;

export function ToggleItemMark(arg1:number,arg2:boolean):Promise<void>;

export function UpdateItem(arg1:database.Item):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;
