// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentSearch(arg1) {
  return window['go']['main']['App']['AddRecentSearch'](arg1);
}

export function CheckpointDatabase() {
  return window['go']['main']['App']['CheckpointDatabase']();
}

export function CleanOrphanedLinks() {
  return window['go']['main']['App']['CleanOrphanedLinks']();
}

export function CreateItem(arg1) {
  return window['go']['main']['App']['CreateItem'](arg1);
}

export function CreateLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLink'](arg1, arg2, arg3);
}

export function CreateLinkOrRemoveTags(arg1, arg2) {
  return window['go']['main']['App']['CreateLinkOrRemoveTags'](arg1, arg2);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function DeleteItemImage(arg1) {
  return window['go']['main']['App']['DeleteItemImage'](arg1);
}

export function DeleteLink(arg1) {
  return window['go']['main']['App']['DeleteLink'](arg1);
}

export function DeleteLinkByItems(arg1, arg2) {
  return window['go']['main']['App']['DeleteLinkByItems'](arg1, arg2);
}

export function DeleteLiteraryTerm(arg1) {
  return window['go']['main']['App']['DeleteLiteraryTerm'](arg1);
}

export function DeleteSavedSearch(arg1) {
  return window['go']['main']['App']['DeleteSavedSearch'](arg1);
}

export function ExportToJSON() {
  return window['go']['main']['App']['ExportToJSON']();
}

export function ExportToMarkdown() {
  return window['go']['main']['App']['ExportToMarkdown']();
}

export function GetAllCliches() {
  return window['go']['main']['App']['GetAllCliches']();
}

export function GetAllItems() {
  return window['go']['main']['App']['GetAllItems']();
}

export function GetAllLinks() {
  return window['go']['main']['App']['GetAllLinks']();
}

export function GetAllLiteraryTerms() {
  return window['go']['main']['App']['GetAllLiteraryTerms']();
}

export function GetAllNames() {
  return window['go']['main']['App']['GetAllNames']();
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetAllSources() {
  return window['go']['main']['App']['GetAllSources']();
}

export function GetDanglingLinks() {
  return window['go']['main']['App']['GetDanglingLinks']();
}

export function GetDatabaseFileSize() {
  return window['go']['main']['App']['GetDatabaseFileSize']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetDuplicateItems() {
  return window['go']['main']['App']['GetDuplicateItems']();
}

export function GetEnvLocation() {
  return window['go']['main']['App']['GetEnvLocation']();
}

export function GetEnvVars() {
  return window['go']['main']['App']['GetEnvVars']();
}

export function GetExtendedStats() {
  return window['go']['main']['App']['GetExtendedStats']();
}

export function GetImageCacheInfo() {
  return window['go']['main']['App']['GetImageCacheInfo']();
}

export function GetItem(arg1) {
  return window['go']['main']['App']['GetItem'](arg1);
}

export function GetItemByWord(arg1) {
  return window['go']['main']['App']['GetItemByWord'](arg1);
}

export function GetItemImage(arg1) {
  return window['go']['main']['App']['GetItemImage'](arg1);
}

export function GetItemLinks(arg1) {
  return window['go']['main']['App']['GetItemLinks'](arg1);
}

export function GetItemsWithUnknownTypes() {
  return window['go']['main']['App']['GetItemsWithUnknownTypes']();
}

export function GetItemsWithoutDefinitions() {
  return window['go']['main']['App']['GetItemsWithoutDefinitions']();
}

export function GetLinkedItemsNotInDefinition() {
  return window['go']['main']['App']['GetLinkedItemsNotInDefinition']();
}

export function GetMarkedItems() {
  return window['go']['main']['App']['GetMarkedItems']();
}

export function GetNavigationHistory() {
  return window['go']['main']['App']['GetNavigationHistory']();
}

export function GetOrphanedItems() {
  return window['go']['main']['App']['GetOrphanedItems']();
}

export function GetRandomItem() {
  return window['go']['main']['App']['GetRandomItem']();
}

export function GetRecentItems(arg1) {
  return window['go']['main']['App']['GetRecentItems'](arg1);
}

export function GetRecentSearches() {
  return window['go']['main']['App']['GetRecentSearches']();
}

export function GetSavedSearches() {
  return window['go']['main']['App']['GetSavedSearches']();
}

export function GetSelfReferentialItems() {
  return window['go']['main']['App']['GetSelfReferentialItems']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTTSCacheInfo() {
  return window['go']['main']['App']['GetTTSCacheInfo']();
}

export function GetTopHubs(arg1) {
  return window['go']['main']['App']['GetTopHubs'](arg1);
}

export function GetUnknownTags() {
  return window['go']['main']['App']['GetUnknownTags']();
}

export function GetUnlinkedReferences() {
  return window['go']['main']['App']['GetUnlinkedReferences']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MergeDuplicateItems(arg1, arg2) {
  return window['go']['main']['App']['MergeDuplicateItems'](arg1, arg2);
}

export function MergeLiteraryTerm(arg1) {
  return window['go']['main']['App']['MergeLiteraryTerm'](arg1);
}

export function RemoveRecentSearch(arg1) {
  return window['go']['main']['App']['RemoveRecentSearch'](arg1);
}

export function RunAdHocQuery(arg1) {
  return window['go']['main']['App']['RunAdHocQuery'](arg1);
}

export function SaveCurrentSearch(arg1) {
  return window['go']['main']['App']['SaveCurrentSearch'](arg1);
}

export function SaveIncomingCollapsed(arg1) {
  return window['go']['main']['App']['SaveIncomingCollapsed'](arg1);
}

export function SaveItemImage(arg1, arg2) {
  return window['go']['main']['App']['SaveItemImage'](arg1, arg2);
}

export function SaveLastView(arg1) {
  return window['go']['main']['App']['SaveLastView'](arg1);
}

export function SaveLastWord(arg1) {
  return window['go']['main']['App']['SaveLastWord'](arg1);
}

export function SaveLeftbarWidth(arg1) {
  return window['go']['main']['App']['SaveLeftbarWidth'](arg1);
}

export function SaveOutgoingCollapsed(arg1) {
  return window['go']['main']['App']['SaveOutgoingCollapsed'](arg1);
}

export function SaveReportItemHealthCollapsed(arg1) {
  return window['go']['main']['App']['SaveReportItemHealthCollapsed'](arg1);
}

export function SaveReportLinkIntegrityCollapsed(arg1) {
  return window['go']['main']['App']['SaveReportLinkIntegrityCollapsed'](arg1);
}

export function SaveRevealMarkdown(arg1) {
  return window['go']['main']['App']['SaveRevealMarkdown'](arg1);
}

export function SaveSearch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSearch'](arg1, arg2, arg3, arg4);
}

export function SaveTabSelection(arg1, arg2) {
  return window['go']['main']['App']['SaveTabSelection'](arg1, arg2);
}

export function SaveTableSort(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveTableSort'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveWindowPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWindowPosition'](arg1, arg2, arg3, arg4);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}

export function SearchItemsWithOptions(arg1) {
  return window['go']['main']['App']['SearchItemsWithOptions'](arg1);
}

export function SelectExportFolder() {
  return window['go']['main']['App']['SelectExportFolder']();
}

export function SpeakWord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SpeakWord'](arg1, arg2, arg3, arg4);
}

export function ToggleItemMark(arg1, arg2) {
  return window['go']['main']['App']['ToggleItemMark'](arg1, arg2);
}

export function UpdateItem(arg1) {
  return window['go']['main']['App']['UpdateItem'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
